services:
  # A Docker web service
  - type: web
    name: url-shortener
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: python.exe -m pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT